#!/usr/bin/env bash


prefix="package_$2"

if [[ "package_confluent_cc_confluent_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_confluent_cc_confluent_volume
	fi
	
